server {
    listen 8080 default_server;
    listen [::]:8080 default_server;

    server_name _;
    root /var/www/moodle/public;
    index index.php index.html;

    client_max_body_size 256M;
    server_tokens off;

    location / {
        try_files $uri $uri/ /r.php?$query_string;
    }

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        error_page 418 = @moodlerouter;
        if (!-f $document_root$fastcgi_script_name) {
            return 418;
        }
        fastcgi_index index.php;
        fastcgi_pass 127.0.0.1:9000;
        include fastcgi_params;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SERVER_PORT $moodle_server_port;
        fastcgi_read_timeout 300s;
        fastcgi_buffers 16 32k;
        fastcgi_buffer_size 64k;
    }

    location @moodlerouter {
        fastcgi_pass 127.0.0.1:9000;
        include fastcgi_params;
        fastcgi_param PATH_INFO "";
        fastcgi_param SCRIPT_NAME /r.php;
        fastcgi_param SCRIPT_FILENAME $document_root/r.php;
        fastcgi_param SERVER_PORT $moodle_server_port;
        fastcgi_read_timeout 300s;
        fastcgi_buffers 16 32k;
        fastcgi_buffer_size 64k;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location = /health {
        access_log off;
        return 200 "OK\n";
    }
}
