worker_processes auto;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    tcp_nopush on;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    client_body_temp_path /tmp/nginx/client_temp;
    fastcgi_temp_path /tmp/nginx/fastcgi_temp;
    proxy_temp_path /tmp/nginx/proxy_temp;
    scgi_temp_path /tmp/nginx/scgi_temp;
    uwsgi_temp_path /tmp/nginx/uwsgi_temp;

    gzip on;

    map $http_host $moodle_server_port {
        default $server_port;
        "~:(?<moodlehostport>[0-9]+)$" $moodlehostport;
    }

    include /etc/nginx/conf.d/*.conf;
}
